apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-richard
  name: nginx-richard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-richard
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-richard
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
