apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-rachel
  name: nginx-rachel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rachel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-rachel
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
